GET http://localhost:8080/user/findall
###
POST http://localhost:8080/user/delete
Content-Type: application/json

{
  "userid": 1
}
###
DELETE http://localhost:8080/user/delete/1

###
POST http://localhost:8080/user/deletebean
Content-Type: application/json

{
  "userid": 1
}
###
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "username": "3435Gerald Weaver",
  "password": "345345345",
  "identity": "345345",
  "userstate": "0",
  "remark": "3453535"
}

###
